/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import dao.NasabahDAO;
import dao.PelunasanDAO;
import daoimpl.NasabahDAOimpl;
import daoimpl.PelunasanDAOimpl;
import java.beans.Beans;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Nasabah;
import model.Pelunasan;

/**
 *
 * @author RuliKA
 */
public class PelunasanForm extends javax.swing.JDialog {

    /**
     * Creates new form PelunasanForm
     */
    public PelunasanForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        isicombo();
        if (!Beans.isDesignTime()) {
            PegadaianPUEntityManager.getTransaction().begin();
        }
        txtID.setVisible(false);
        txtIDnasabah.setVisible(false);
    }
    
    public void refreshTable(){
        txtKodePelunasan.setText(null);
        txtJmlPelunasan.setText(null);
        txtStatusPelunasan.setText(null);

        //tabelPelunasan = new javax.swing.JTable();
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        PegadaianPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PegadaianPU").createEntityManager();
        pelunasanQuery = java.beans.Beans.isDesignTime() ? null : PegadaianPUEntityManager.createQuery("SELECT p FROM Pelunasan p");
        pelunasanList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pelunasanQuery.getResultList();
        
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pelunasanList, tabelPelunasan);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${kodePelunasan}"));
        columnBinding.setColumnName("Kode Pelunasan");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nasabah.namaNasabah}"));
        columnBinding.setColumnName("Nasabah");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jmlPelunasan}"));
        columnBinding.setColumnName("Jml Pelunasan");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${statusPelunasan}"));
        columnBinding.setColumnName("Status Pelunasan");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tglPelunasan}"));
        columnBinding.setColumnName("Tgl Pelunasan");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(tabelPelunasan);
        bindingGroup.bind();
    }
    
    public void isicombo() {
        NasabahDAO ndao = new NasabahDAOimpl();
        ndao.getAll().stream().forEach((n) -> {
        comboNasabah.addItem(n.getNamaNasabah());
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        PegadaianPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("PegadaianPU").createEntityManager();
        pelunasanQuery = java.beans.Beans.isDesignTime() ? null : PegadaianPUEntityManager.createQuery("SELECT p FROM Pelunasan p");
        pelunasanList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pelunasanQuery.getResultList();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        pelunasanQuery1 = java.beans.Beans.isDesignTime() ? null : PegadaianPUEntityManager.createQuery("SELECT p FROM Pelunasan p");
        pelunasanList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : pelunasanQuery1.getResultList();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodePelunasan = new javax.swing.JTextField();
        txtJmlPelunasan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        comboNasabah = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPelunasan = new javax.swing.JTable();
        txtIDnasabah = new javax.swing.JTextField();
        txtStatusPelunasan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Form Data Pelunasan");

        jLabel2.setText("Kode Pelunasan :");

        jLabel4.setText("Jumlah Pelunasan :");

        jLabel5.setText("Nama Nasabah :");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tabelPelunasan, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.kodePelunasan}"), txtKodePelunasan, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tabelPelunasan, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.jmlPelunasan}"), txtJmlPelunasan, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel6.setText("Cari Berdasarkan Nama :");

        jLabel7.setText("Status :");

        btnCetak.setText("Cetak");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tabelPelunasan, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.id}"), txtID, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, pelunasanList, tabelPelunasan);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${kodePelunasan}"));
        columnBinding.setColumnName("Kode Pelunasan");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nasabah.namaNasabah}"));
        columnBinding.setColumnName("Nasabah");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${jmlPelunasan}"));
        columnBinding.setColumnName("Jml Pelunasan");
        columnBinding.setColumnClass(Long.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${statusPelunasan}"));
        columnBinding.setColumnName("Status Pelunasan");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tglPelunasan}"));
        columnBinding.setColumnName("Tgl Pelunasan");
        columnBinding.setColumnClass(java.util.Date.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tabelPelunasan);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tabelPelunasan, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.statusPelunasan}"), txtStatusPelunasan, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDnasabah, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 18, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtKodePelunasan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboNasabah, javax.swing.GroupLayout.Alignment.LEADING, 0, 145, Short.MAX_VALUE))
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJmlPelunasan)
                            .addComponent(txtStatusPelunasan))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(btnCetak))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodePelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboNasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtJmlPelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtStatusPelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnUbah)
                            .addComponent(btnHapus)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDnasabah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    PelunasanDAO pdao = new PelunasanDAOimpl();
//    int TAG = 0;
//    int ID;
    
//    boolean validasi(){
//        return !txtKodePelunasan.getText().isEmpty() && !txtJmlPelunasan.getText().isEmpty() && !txtStatusPelunasan.getText().isEmpty();
//    }
    
//    public void tambah(){
//        if(validasi()){
//            Pelunasan p = new Pelunasan();
//            PelunasanDAO pdao = new PelunasanDAOimpl();
//            NasabahDAO ndao = new NasabahDAOimpl();
//            p.setJmlPelunasan(Long.parseLong(txtJmlPelunasan.getText()));
//            p.setKodePelunasan(txtKodePelunasan.getText());
//            p.setStatusPelunasan(txtStatusPelunasan.getText());
//            p.setTglPelunasan(Date.from(Instant.now())); 
//            p.setNasabah(txtNamaNasabah.getText());
//            p.setNasabah(ndao.getById(Long.parseLong(txtIDnasabah.getText())));
//            p.setNasabah(ndao.getByNama(comboNasabah.getSelectedItem().toString()));
//            p.setNasabah(ndao.getByNama(String.valueOf(txtNamaNasabah.getText())));
//            p.setNasabah(txtNamaNasabah.getText());
//            pdao.insert(p);
//            refreshTable();
//        } else {
//            JOptionPane.showMessageDialog(rootPane, "Data Tidak Lengkap");
//        }
//    }
    
    
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        //tambah();
            Pelunasan p = new Pelunasan();
            PelunasanDAO pdao = new PelunasanDAOimpl();
            NasabahDAO ndao = new NasabahDAOimpl();
            p.setJmlPelunasan(Long.parseLong(txtJmlPelunasan.getText()));
            p.setKodePelunasan(txtKodePelunasan.getText());
            p.setStatusPelunasan(txtStatusPelunasan.getText());
            p.setTglPelunasan(Date.from(Instant.now()));
            p.setNasabah(ndao.getByNama(comboNasabah.getSelectedItem().toString()));
            pdao.insert(p);
            refreshTable();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        PelunasanDAO pdao = new PelunasanDAOimpl();
        Pelunasan p = pdao.getById(Long.parseLong(txtID.getText()));
        p.setKodePelunasan(txtKodePelunasan.getText());
        p.setJmlPelunasan(Long.parseLong(txtJmlPelunasan.getText()));
        p.setStatusPelunasan(txtStatusPelunasan.getText());
        pdao.update(p);
        refreshTable();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        PelunasanDAO pdao = new PelunasanDAOimpl();
        Pelunasan p = pdao.getById(Long.parseLong(txtID.getText()));
        pdao.delete(p);
        refreshTable();
    }//GEN-LAST:event_btnHapusActionPerformed
//        NasabahDAO ndao = new NasabahDAOimpl();
//        String nama = comboNasabah.getSelectedItem().toString();
//        Nasabah n = ndao.getByNama(nama);
//        txtIDnasabah.setText(n.getId().toString());
//        txtNamaNasabah.setText(String.valueOf(nama));
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PelunasanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PelunasanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PelunasanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PelunasanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PelunasanForm dialog = new PelunasanForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager PegadaianPUEntityManager;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> comboNasabah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private java.util.List<model.Pelunasan> pelunasanList;
    private java.util.List<model.Pelunasan> pelunasanList1;
    private javax.persistence.Query pelunasanQuery;
    private javax.persistence.Query pelunasanQuery1;
    private javax.swing.JTable tabelPelunasan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDnasabah;
    private javax.swing.JTextField txtJmlPelunasan;
    private javax.swing.JTextField txtKodePelunasan;
    private javax.swing.JTextField txtStatusPelunasan;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
